import { useState, useEffect, useMemo } from 'react';
import Head from 'next/head';
import { 
  LeftArrowIcon, 
  LogoImg, 
  ProductsActiveIcon, 
  PromotionsIcon, 
  CalculationsInactiveIcon 
} from '../assets';
import Image from 'next/image';
import { Product } from '@/components';
import { getProductsList } from '@/services';
import styles from '../styles/Home.module.css';

const Home = () => {
  const [data, setData] = useState();

  useEffect(() => {
    getProductsList(setData);
  }, []);

  const memoizedData = useMemo(() => data, [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <Image
            className={styles.logo}
            src={LogoImg}
            alt="Лого"
          />
        </header>
        <h1>
          <span>
            <Image
              className={styles.logo}
              src={LeftArrowIcon}
              alt="Иконка возврата"
            />
          </span>
          <span>Кровати</span>
        </h1>
        <ul className={styles.list}>
          {memoizedData?.map(({
            title,
            image,
            price,
          }) => <li className={styles.item}>
            <Product
              title={title}
              src={image}
              price={price}
            />
          </li>)}
        </ul>
        <footer className={styles.footer}>
          <Image
            className={styles['menu-item']}
            src={ProductsActiveIcon}
            alt="Иконка изделий"
          />
          <Image
            className={styles['menu-item']}
            src={PromotionsIcon}
            alt="Иконка акций"
          />
          <Image
            className={styles['menu-item']}
            src={CalculationsInactiveIcon}
            alt="Иконка расчетов"
          />
        </footer>
      </main>
    </>
  )
};

export default Home;